### ISSUE TITLE
Set requirments.txt for interpretator

### ISSUE THREAD

**Issue by Samenster** [filipehlreis/22_modern_ui_tutorial#1]

**Comment by filipehlreis** [comment]
Hi Samenster, how do you do?
I just created the requirements.txt, check it out :)

If you need any help, just ask 😄

**Comment by filipehlreis** [comment]
Maybe you'll need to install this program to run the Custom Widgets.

https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer/releases

**Comment by Samenster** [comment]
> Maybe you'll need to install this program to run the Custom Widgets.
> 
> https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer/releases

Yes, you are right. Now i use another template application. Same author, but without library Customs Widgets.
